# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  node_server:
    build:
      target: runner # Uses the production target stage
    command: node dist/index.js # Explicitly run the compiled binary
